### ISSUE TITLE
need better pointer for configuration errors

### ISSUE THREAD

**Issue by willkg** [mozilla/antenna#21]
@peterbe hit this today:

```
Traceback (most recent call last):
  File "/Users/peterbe/virtualenvs/antenna/lib/python2.7/site-packages/gunicorn/arbiter.py", line 517, in spawn_worker
    worker.init_process()
  File "/Users/peterbe/virtualenvs/antenna/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
    super(GeventWorker, self).init_process()
  File "/Users/peterbe/virtualenvs/antenna/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/peterbe/virtualenvs/antenna/lib/python2.7/site-packages/gunicorn/workers/base.py", line 132, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/peterbe/virtualenvs/antenna/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/peterbe/virtualenvs/antenna/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/peterbe/virtualenvs/antenna/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/peterbe/virtualenvs/antenna/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/peterbe/virtualenvs/antenna/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/Users/peterbe/dev/MOZILLA/SOCORRO/antenna/antenna/wsgi.py", line 1, in <module>
    from antenna.app import get_app
  File "/Users/peterbe/virtualenvs/antenna/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/Users/peterbe/dev/MOZILLA/SOCORRO/antenna/antenna/app.py", line 51, in <module>
    class HealthCheckResource(object):
  File "/Users/peterbe/dev/MOZILLA/SOCORRO/antenna/antenna/app.py", line 53, in HealthCheckResource
    username=config('USERNAME', namespace='healthcheck'),
  File "/Users/peterbe/dev/MOZILLA/SOCORRO/antenna/antenna/configlib.py", line 280, in __call__
    return self.config.__call__(*args, **kwargs)
  File "/Users/peterbe/dev/MOZILLA/SOCORRO/antenna/antenna/configlib.py", line 257, in __call__
    key, namespace, parser)
ConfigurationError: USERNAME (healthcheck) requires a value parseable by <type 'str'>
```

This should be covered by documentation, but that's covered in a different issue and isn't done, yet.

However, even if we had documentation, this line doesn't help the programmer know what to do:

```
ConfigurationError: USERNAME (healthcheck) requires a value parseable by <type 'str'>
```

If you're using environment variables, then you want to include `HEALTHCHECK_USERNAME=foo`, but if you're using ini files, then you want:

```
[healthcheck]
username=foo
```

We could try to stuff all that into that line, but I think it'd be better to include a url to the appropriate docs.

Anyhow, this issue covers making this more helpful.

**Comment by willkg** [comment]
I made some changes to Everett so the error message is a little bit better, however it still doesn't point you anywhere for documentation. That'd be nice.

I added https://github.com/willkg/everett/issues/41 to Everett to cover this.

**Comment by willkg** [comment]
Landed the changes in everett. Going to close this.
